In [1]:
import pandas as pd
import numpy as np
%matplotlib
from pandas import read_csv

Using matplotlib backend: <object object at 0x124207630>

In [2]:
filename_1 = 'Garage.csv'
df_1 = read_csv(filename_1)
display(df_1)

,Id,GarageType,GarageYrBlt,GarageCars,GarageArea,GarageQual,GarageCond
0,186,Detached,1993.0,3,840.0,Ex,TA
1,241,Attchd,2008.0,2,750.0,TA,TA
2,125,Attchd,1979.0,2,435.0,TA,TA
3,210,Attchd,1964.0,2,504.0,TA,Gd
4,1262,Attchd,1956.0,1,338.0,TA,TA
...,...,...,...,...,...,...,...
1455,903,Attchd,2003.0,2,393.0,TA,TA
1456,589,Attchd,1968.0,1,452.0,TA,TA
1457,498,Detchd,1925.0,1,240.0,TA,TA
1458,25,Attchd,1968.0,1,270.0,TA,TA
1459,487,Attchd,1965.0,2,515.0,TA,TA

In [3]:
df_1.nunique()

Id             1454
GarageType        9
GarageYrBlt      97
GarageCars        5
GarageArea      441
GarageQual        5
GarageCond        5
dtype: int64

In [4]:
df_1['GarageType'].value_counts()

Attchd      862
Detchd      364
BuiltIn      88
Detached     21
Basment      14
Attached     10
CarPort       9
2Types        6
Basement      5
Name: GarageType, dtype: int64

In [5]:
df_1['GarageType'] = df_1['GarageType'].fillna('Attchd')
display(df_1)

,Id,GarageType,GarageYrBlt,GarageCars,GarageArea,GarageQual,GarageCond
0,186,Detached,1993.0,3,840.0,Ex,TA
1,241,Attchd,2008.0,2,750.0,TA,TA
2,125,Attchd,1979.0,2,435.0,TA,TA
3,210,Attchd,1964.0,2,504.0,TA,Gd
4,1262,Attchd,1956.0,1,338.0,TA,TA
...,...,...,...,...,...,...,...
1455,903,Attchd,2003.0,2,393.0,TA,TA
1456,589,Attchd,1968.0,1,452.0,TA,TA
1457,498,Detchd,1925.0,1,240.0,TA,TA
1458,25,Attchd,1968.0,1,270.0,TA,TA
1459,487,Attchd,1965.0,2,515.0,TA,TA

In [6]:
df_1.groupby('GarageType')['GarageArea'].sum()

GarageType
2Types        5517.000000
Attached     11570.000000
Attchd      484026.391097
Basement      2130.000000
Basment       6253.000000
BuiltIn      51004.000000
CarPort       4062.000000
Detached      8899.000000
Detchd      155875.000000
Name: GarageArea, dtype: float64

In [7]:
df_1.groupby('GarageType')['GarageArea'].count()

GarageType
2Types        6
Attached     10
Attchd      943
Basement      5
Basment      14
BuiltIn      88
CarPort       9
Detached     21
Detchd      364
Name: GarageArea, dtype: int64

In [8]:
filename_2 = 'Property.csv'
df_2 = read_csv(filename_2)
display(df_2)

,Id,LotArea,Street,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,TotalBsmtSF,Heating,...,Fireplaces,FireplaceQu,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC
0,1,8450,Pave,7,5,2003,2003,Gable,856,GasA,...,0,NaN,Y,0,61,0,0,0,0,NaN
1,2,9600,Pave,6,8,1976,1976,Gable,1262,GasA,...,1,TA,Y,298,0,0,0,0,0,NaN
2,3,11250,Pave,7,5,2001,2002,Gable,920,GasA,...,1,TA,Y,0,42,0,0,0,0,NaN
3,4,9550,Pave,7,5,1915,1970,Gable,756,GasA,...,1,Gd,Y,0,35,272,0,0,0,NaN
4,5,14260,Pave,8,5,2000,2000,Gable,1145,GasA,...,1,TA,Y,192,84,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,7917,Pave,6,5,1999,2000,Gable,953,GasA,...,1,TA,Y,0,40,0,0,0,0,NaN
1456,1457,13175,Pave,6,6,1978,1988,Gable,1542,GasA,...,2,TA,Y,349,0,0,0,0,0,NaN
1457,1458,9042,Pave,7,9,1941,2006,Gable,1152,GasA,...,2,Gd,Y,0,60,0,0,0,0,NaN
1458,1459,9717,Pave,5,6,1950,1996,Hip,1078,GasA,...,0,NaN,Y,366,0,112,0,0,0,NaN
1459,1460,9937,Pave,5,6,1965,1965,Gable,1256,GasA,...,0,NaN,Y,736,68,0,0,0,0,NaN

In [14]:
df_2[ (df_2['BsmtFullBath']==0) | (df_2['Fireplaces']==0) ]

,Id,LotArea,Street,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,TotalBsmtSF,Heating,...,Fireplaces,FireplaceQu,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC
0,1,8450,Pave,7,5,2003,2003,Gable,856,GasA,...,0,NaN,Y,0,61,0,0,0,0,NaN
1,2,9600,Pave,6,8,1976,1976,Gable,1262,GasA,...,1,TA,Y,298,0,0,0,0,0,NaN
5,6,14115,Pave,5,5,1993,1995,Gable,796,GasA,...,0,NaN,Y,40,30,0,320,0,0,NaN
8,9,6120,Pave,7,5,1931,1950,Gable,952,GasA,...,2,TA,Y,90,0,205,0,0,0,NaN
10,11,11200,Pave,5,5,1965,1965,Hip,1040,GasA,...,0,NaN,Y,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,1455,7500,Pave,7,5,2004,2005,Gable,1221,GasA,...,0,NaN,Y,0,113,0,0,0,0,NaN
1455,1456,7917,Pave,6,5,1999,2000,Gable,953,GasA,...,1,TA,Y,0,40,0,0,0,0,NaN
1457,1458,9042,Pave,7,9,1941,2006,Gable,1152,GasA,...,2,Gd,Y,0,60,0,0,0,0,NaN
1458,1459,9717,Pave,5,6,1950,1996,Hip,1078,GasA,...,0,NaN,Y,366,0,112,0,0,0,NaN
1459,1460,9937,Pave,5,6,1965,1965,Gable,1256,GasA,...,0,NaN,Y,736,68,0,0,0,0,NaN

In [15]:
df_2['LotArea'].max()

215245

In [16]:
filename_3 = 'Transaction.csv'
df_3 = read_csv(filename_3)
display(df_3)

        Id  MoSold  YrSold  SalePrice
0     1362       6    2009     260000
1      859       6    2009     152000
2     1042       7    2008     173000
3     1424       8    2006     274970
4      126       6    2006      84500
...    ...     ...     ...        ...
1464   682       7    2009     159434
1465  1196       7    2008     176000
1466   434       7    2008     181000
1467   399      11    2007      67000
1468   898       6    2009     142953

[1469 rows x 4 columns]

In [17]:
df_3.nunique()

Id           1460
MoSold         12
YrSold          5
SalePrice     663
dtype: int64

In [19]:
df_3 = df_3.drop_duplicates()

In [20]:
display(df_3)

        Id  MoSold  YrSold  SalePrice
0     1362       6    2009     260000
1      859       6    2009     152000
2     1042       7    2008     173000
3     1424       8    2006     274970
4      126       6    2006      84500
...    ...     ...     ...        ...
1464   682       7    2009     159434
1465  1196       7    2008     176000
1466   434       7    2008     181000
1467   399      11    2007      67000
1468   898       6    2009     142953

[1460 rows x 4 columns]

In [22]:
df_merge = pd.merge(df_2, df_3, on='Id')
display(df_merge)

,Id,LotArea,Street,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,TotalBsmtSF,Heating,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,MoSold,YrSold,SalePrice
0,1,8450,Pave,7,5,2003,2003,Gable,856,GasA,...,0,61,0,0,0,0,NaN,2,2008,208500
1,2,9600,Pave,6,8,1976,1976,Gable,1262,GasA,...,298,0,0,0,0,0,NaN,5,2007,181500
2,3,11250,Pave,7,5,2001,2002,Gable,920,GasA,...,0,42,0,0,0,0,NaN,9,2008,223500
3,4,9550,Pave,7,5,1915,1970,Gable,756,GasA,...,0,35,272,0,0,0,NaN,2,2006,140000
4,5,14260,Pave,8,5,2000,2000,Gable,1145,GasA,...,192,84,0,0,0,0,NaN,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,7917,Pave,6,5,1999,2000,Gable,953,GasA,...,0,40,0,0,0,0,NaN,8,2007,175000
1456,1457,13175,Pave,6,6,1978,1988,Gable,1542,GasA,...,349,0,0,0,0,0,NaN,2,2010,210000
1457,1458,9042,Pave,7,9,1941,2006,Gable,1152,GasA,...,0,60,0,0,0,0,NaN,5,2010,266500
1458,1459,9717,Pave,5,6,1950,1996,Hip,1078,GasA,...,366,0,112,0,0,0,NaN,4,2010,142125
1459,1460,9937,Pave,5,6,1965,1965,Gable,1256,GasA,...,736,68,0,0,0,0,NaN,6,2008,147500

In [23]:
df_merge[df_merge['CentralAir'] == 'Y']['SalePrice'].max()

755000

In [27]:
df_merge[df_merge['YearBuilt'] == 2007]['SalePrice'].sum()

12512774

In [28]:
df_merge[df_merge['YearBuilt'] == 2007]['SalePrice'].count()

49

In [29]:
print('the average Property Price for properties built in 2007: ', 12512774/49)

the average Property Price for properties built in 2007:  255362.73469387754

In [30]:
df_merge[df_merge['YearBuilt'] == 1900]['SalePrice'].sum()

1124926

In [31]:
df_merge[df_merge['YearBuilt'] == 1900]['SalePrice'].count()

10

In [32]:
print('the average Property Price for properties built in 1900: ', 1124926/10)

the average Property Price for properties built in 1900:  112492.6

In [33]:
print('the average Property Price for properties built in 2007 vs 1900: ', 255362.73469387754-112492.6)

the average Property Price for properties built in 2007 vs 1900:  142870.13469387754

In [35]:
import pandas as pd
property_combined = pd.read_csv("Combined.csv")
display(property_combined)

,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea
0,8450,7,5,2003,856,856,854,1710,3,1,8,0,2,548
1,9600,6,8,1976,1262,1262,0,1262,3,1,6,1,2,460
2,11250,7,5,2001,920,920,866,1786,3,1,6,1,2,608
3,9550,7,5,1915,756,961,756,1717,3,1,7,1,3,642
4,14260,8,5,2000,1145,1145,1053,2198,4,1,9,1,3,836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,7917,6,5,1999,953,953,694,1647,3,1,7,1,2,460
1456,13175,6,6,1978,1542,2073,0,2073,3,1,7,2,2,500
1457,9042,7,9,1941,1152,1188,1152,2340,4,1,9,2,1,252
1458,9717,5,6,1950,1078,1078,0,1078,2,1,5,0,1,240
1459,9937,5,6,1965,1256,1256,0,1256,3,1,6,0,1,276

In [38]:
property_combined.corr()

,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea
LotArea,1.000000,0.105806,-0.005636,0.014228,0.260833,0.299475,0.050986,0.263116,0.119690,-0.017784,0.190015,0.271364,0.154871,0.180403
OverallQual,0.105806,1.000000,-0.091932,0.572323,0.537808,0.476224,0.295493,0.593007,0.101676,-0.183882,0.427452,0.396765,0.600671,0.562022
OverallCond,-0.005636,-0.091932,1.000000,-0.375983,-0.171098,-0.144203,0.028942,-0.079686,0.012980,-0.087001,-0.057583,-0.023820,-0.185758,-0.151521
YearBuilt,0.014228,0.572323,-0.375983,1.000000,0.391452,0.281986,0.010308,0.199010,-0.070651,-0.174800,0.095589,0.147716,0.537850,0.478954
TotalBsmtSF,0.260833,0.537808,-0.171098,0.391452,1.000000,0.819530,-0.174512,0.454868,0.050450,-0.068901,0.285573,0.339519,0.434585,0.486665
1stFlrSF,0.299475,0.476224,-0.144203,0.281986,0.819530,1.000000,-0.202646,0.566024,0.127401,0.068101,0.409516,0.410531,0.439317,0.489782
2ndFlrSF,0.050986,0.295493,0.028942,0.010308,-0.174512,-0.202646,1.000000,0.687501,0.502901,0.059306,0.616423,0.194561,0.183926,0.138347
GrLivArea,0.263116,0.593007,-0.079686,0.199010,0.454868,0.566024,0.687501,1.000000,0.521270,0.100063,0.825489,0.461679,0.467247,0.468997
BedroomAbvGr,0.119690,0.101676,0.012980,-0.070651,0.050450,0.127401,0.502901,0.521270,1.000000,0.198597,0.676620,0.107570,0.086106,0.065253
KitchenAbvGr,-0.017784,-0.183882,-0.087001,-0.174800,-0.068901,0.068101,0.059306,0.100063,0.198597,1.000000,0.256045,-0.123936,-0.050634,-0.064433
TotRmsAbvGrd,0.190015,0.427452,-0.057583,0.095589,0.285573,0.409516,0.616423,0.825489,0.676620,0.256045,1.000000,0.326114,0.362289,0.337822
Fireplaces,0.271364,0.396765,-0.023820,0.147716,0.339519,0.410531,0.194561,0.461679,0.107570,-0.123936,0.326114,1.000000,0.300789,0.269141
GarageCars,0.154871,0.600671,-0.185758,0.537850,0.434585,0.439317,0.183926,0.467247,0.086106,-0.050634,0.362289,0.300789,1.000000,0.882475
GarageArea,0.180403,0.562022,-0.151521,0.478954,0.486665,0.489782,0.138347,0.468997,0.065253,-0.064433,0.337822,0.269141,0.882475,1.000000

In [39]:
property_combined['Indoor area'] = property_combined['TotalBsmtSF'] + property_combined['GrLivArea'] + property_combined['2ndFlrSF']

In [40]:
property_combined['Age of the property'] = 2022 - property_combined['YearBuilt']

In [41]:
display(property_combined)

,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,Indoor area,Age of the property
0,8450,7,5,2003,856,856,854,1710,3,1,8,0,2,548,3420,19
1,9600,6,8,1976,1262,1262,0,1262,3,1,6,1,2,460,2524,46
2,11250,7,5,2001,920,920,866,1786,3,1,6,1,2,608,3572,21
3,9550,7,5,1915,756,961,756,1717,3,1,7,1,3,642,3229,107
4,14260,8,5,2000,1145,1145,1053,2198,4,1,9,1,3,836,4396,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,7917,6,5,1999,953,953,694,1647,3,1,7,1,2,460,3294,23
1456,13175,6,6,1978,1542,2073,0,2073,3,1,7,2,2,500,3615,44
1457,9042,7,9,1941,1152,1188,1152,2340,4,1,9,2,1,252,4644,81
1458,9717,5,6,1950,1078,1078,0,1078,2,1,5,0,1,240,2156,72
1459,9937,5,6,1965,1256,1256,0,1256,3,1,6,0,1,276,2512,57

In [42]:
property_combined.corr()

,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,Indoor area,Age of the property
LotArea,1.000000,0.105806,-0.005636,0.014228,0.260833,0.299475,0.050986,0.263116,0.119690,-0.017784,0.190015,0.271364,0.154871,0.180403,0.260099,-0.014228
OverallQual,0.105806,1.000000,-0.091932,0.572323,0.537808,0.476224,0.295493,0.593007,0.101676,-0.183882,0.427452,0.396765,0.600671,0.562022,0.640006,-0.572323
OverallCond,-0.005636,-0.091932,1.000000,-0.375983,-0.171098,-0.144203,0.028942,-0.079686,0.012980,-0.087001,-0.057583,-0.023820,-0.185758,-0.151521,-0.098668,0.375983
YearBuilt,0.014228,0.572323,-0.375983,1.000000,0.391452,0.281986,0.010308,0.199010,-0.070651,-0.174800,0.095589,0.147716,0.537850,0.478954,0.265642,-1.000000
TotalBsmtSF,0.260833,0.537808,-0.171098,0.391452,1.000000,0.819530,-0.174512,0.454868,0.050450,-0.068901,0.285573,0.339519,0.434585,0.486665,0.569063,-0.391452
1stFlrSF,0.299475,0.476224,-0.144203,0.281986,0.819530,1.000000,-0.202646,0.566024,0.127401,0.068101,0.409516,0.410531,0.439317,0.489782,0.537803,-0.281986
2ndFlrSF,0.050986,0.295493,0.028942,0.010308,-0.174512,-0.202646,1.000000,0.687501,0.502901,0.059306,0.616423,0.194561,0.183926,0.138347,0.682286,-0.010308
GrLivArea,0.263116,0.593007,-0.079686,0.199010,0.454868,0.566024,0.687501,1.000000,0.521270,0.100063,0.825489,0.461679,0.467247,0.468997,0.969783,-0.199010
BedroomAbvGr,0.119690,0.101676,0.012980,-0.070651,0.050450,0.127401,0.502901,0.521270,1.000000,0.198597,0.676620,0.107570,0.086106,0.065253,0.487735,0.070651
KitchenAbvGr,-0.017784,-0.183882,-0.087001,-0.174800,-0.068901,0.068101,0.059306,0.100063,0.198597,1.000000,0.256045,-0.123936,-0.050634,-0.064433,0.045637,0.174800
TotRmsAbvGrd,0.190015,0.427452,-0.057583,0.095589,0.285573,0.409516,0.616423,0.825489,0.676620,0.256045,1.000000,0.326114,0.362289,0.337822,0.783421,-0.095589
Fireplaces,0.271364,0.396765,-0.023820,0.147716,0.339519,0.410531,0.194561,0.461679,0.107570,-0.123936,0.326114,1.000000,0.300789,0.269141,0.450750,-0.147716
GarageCars,0.154871,0.600671,-0.185758,0.537850,0.434585,0.439317,0.183926,0.467247,0.086106,-0.050634,0.362289,0.300789,1.000000,0.882475,0.488580,-0.537850
GarageArea,0.180403,0.562022,-0.151521,0.478954,0.486665,0.489782,0.138347,0.468997,0.065253,-0.064433,0.337822,0.269141,0.882475,1.000000,0.492242,-0.478954
Indoor area,0.260099,0.640006,-0.098668,0.265642,0.569063,0.537803,0.682286,0.969783,0.487735,0.045637,0.783421,0.450750,0.488580,0.492242,1.000000,-0.265642
Age of the property,-0.014228,-0.572323,0.375983,-1.000000,-0.391452,-0.281986,-0.010308,-0.199010,0.070651,0.174800,-0.095589,-0.147716,-0.537850,-0.478954,-0.265642,1.000000

In [43]:
import statsmodels.api as sm

X1 = pd.read_csv("X1.csv")
Y1 = pd.read_csv("Y1.csv")
lm_bad = sm.OLS(Y1, X1)
fit_bad = lm_bad.fit()

In [45]:
display(X1)

,const,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,OpenPorchSF,YrSold,HeatingQC_Fa,HeatingQC_Gd,HeatingQC_Po,HeatingQC_TA,CentralAir_Y
0,1.0,8450,7,5,2003,856,856,1710,2,3,1,4,8,61,2008,0,0,0,0,1
1,1.0,9600,6,8,1976,1262,1262,1262,2,3,1,3,6,0,2007,0,0,0,0,1
2,1.0,11250,7,5,2001,920,920,1786,2,3,1,4,6,42,2008,0,0,0,0,1
3,1.0,9550,7,5,1915,756,961,1717,1,3,1,4,7,35,2006,0,1,0,0,1
4,1.0,14260,8,5,2000,1145,1145,2198,2,4,1,4,9,84,2008,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.0,7917,6,5,1999,953,953,1647,2,3,1,3,7,40,2007,0,0,0,0,1
1456,1.0,13175,6,6,1978,1542,2073,2073,2,3,1,3,7,0,2010,0,0,0,1,1
1457,1.0,9042,7,9,1941,1152,1188,2340,2,4,1,4,9,60,2010,0,0,0,0,1
1458,1.0,9717,5,6,1950,1078,1078,1078,1,2,1,4,5,0,2010,0,1,0,0,1
1459,1.0,9937,5,6,1965,1256,1256,1256,1,3,1,3,6,68,2008,0,1,0,0,1

In [46]:
display(Y1)

      SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [44]:
fit_bad.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.793
Model:                            OLS   Adj. R-squared:                  0.790
Method:                 Least Squares   F-statistic:                     290.4
Date:                Tue, 22 Nov 2022   Prob (F-statistic):               0.00
Time:                        09:44:44   Log-Likelihood:                -17394.
No. Observations:                1460   AIC:                         3.483e+04
Df Residuals:                    1440   BIC:                         3.493e+04
Df Model:                          19
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         -2.91e+05   1.45e+06     -0.200      0.841   -3.14e+06    2.56e+06
LotArea          0.6618      0.102      6.473      0.000       0.461       0.862
OverallQual   1.603e+04   1225.510     13.080      0.000    1.36e+04    1.84e+04
OverallCond   5459.6758   1020.589      5.350      0.000    3457.675    7461.676
YearBuilt      468.2813     52.970      8.840      0.000     364.374     572.188
TotalBsmtSF     17.3972      4.165      4.177      0.000       9.227      25.568
1stFlrSF        15.0904      4.837      3.120      0.002       5.601      24.579
GrLivArea       49.3237      4.160     11.858      0.000      41.164      57.483
FullBath     -1445.9272   2641.035     -0.547      0.584   -6626.615    3734.761
BedroomAbvGr -9484.3446   1738.631     -5.455      0.000   -1.29e+04   -6073.823
KitchenAbvGr -2.343e+04   5048.725     -4.641      0.000   -3.33e+04   -1.35e+04
KitchenQual   1.496e+04   2140.976      6.986      0.000    1.08e+04    1.92e+04
TotRmsAbvGrd  5429.0782   1269.007      4.278      0.000    2939.779    7918.378
OpenPorchSF    -12.3516     15.654     -0.789      0.430     -43.059      18.356
YrSold        -360.3073    721.928     -0.499      0.618   -1776.450    1055.836
HeatingQC_Fa  1909.5771   5919.390      0.323      0.747   -9701.973    1.35e+04
HeatingQC_Gd -3791.3385   2920.857     -1.298      0.194   -9520.929    1938.252
HeatingQC_Po -1.649e+04   3.67e+04     -0.449      0.653   -8.85e+04    5.55e+04
HeatingQC_TA -3216.9434   2639.380     -1.219      0.223   -8394.385    1960.498
CentralAir_Y -5900.4614   4688.257     -1.259      0.208   -1.51e+04    3296.084
==============================================================================
Omnibus:                      750.288   Durbin-Watson:                   1.989
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           121456.015
Skew:                          -1.313   Prob(JB):                         0.00
Kurtosis:                      47.605   Cond. No.                     2.25e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.25e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [48]:
X2 = pd.get_dummies(X1['OverallQual'], drop_first = True, prefix = 'OverallQual')
display(X2)

,OverallQual_2,OverallQual_3,OverallQual_4,OverallQual_5,OverallQual_6,OverallQual_7,OverallQual_8,OverallQual_9,OverallQual_10
0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,1,0,0,0,0
2,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1455,0,0,0,0,1,0,0,0,0
1456,0,0,0,0,1,0,0,0,0
1457,0,0,0,0,0,1,0,0,0
1458,0,0,0,1,0,0,0,0,0
1459,0,0,0,1,0,0,0,0,0

In [49]:
X3 = pd.get_dummies(X1['OverallCond'], drop_first = True, prefix = 'OverallCond')
display(X3)

,OverallCond_2,OverallCond_3,OverallCond_4,OverallCond_5,OverallCond_6,OverallCond_7,OverallCond_8,OverallCond_9
0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,1,0
2,0,0,0,1,0,0,0,0
3,0,0,0,1,0,0,0,0
4,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...
1455,0,0,0,1,0,0,0,0
1456,0,0,0,0,1,0,0,0
1457,0,0,0,0,0,0,0,1
1458,0,0,0,0,1,0,0,0
1459,0,0,0,0,1,0,0,0

In [50]:
X4 = pd.get_dummies(X1['KitchenQual'], drop_first = True, prefix = 'KitchenQual')
display(X4)

      KitchenQual_3  KitchenQual_4  KitchenQual_5
0                 0              1              0
1                 1              0              0
2                 0              1              0
3                 0              1              0
4                 0              1              0
...             ...            ...            ...
1455              1              0              0
1456              1              0              0
1457              0              1              0
1458              0              1              0
1459              1              0              0

[1460 rows x 3 columns]

In [59]:
X_11 = pd.merge(X1, X2, left_index=True, right_index=True)
X_11 = pd.merge(X_11, X3, left_index=True, right_index=True)
X_11 = pd.merge(X_11, X4, left_index=True, right_index=True)

In [79]:
X_11 = X_11.drop(['OverallCond'], axis=1)
X_11 = X_11.drop(['OverallQual'], axis=1)
X_11 = X_11.drop(['KitchenQual'], axis=1)

In [80]:
display(X_11)

,const,LotArea,YearBuilt,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,...,OverallCond_3,OverallCond_4,OverallCond_5,OverallCond_6,OverallCond_7,OverallCond_8,OverallCond_9,KitchenQual_3,KitchenQual_4,KitchenQual_5
0,1.0,8450,2003,856,856,1710,2,3,1,8,...,0,0,1,0,0,0,0,0,1,0
1,1.0,9600,1976,1262,1262,1262,2,3,1,6,...,0,0,0,0,0,1,0,1,0,0
2,1.0,11250,2001,920,920,1786,2,3,1,6,...,0,0,1,0,0,0,0,0,1,0
3,1.0,9550,1915,756,961,1717,1,3,1,7,...,0,0,1,0,0,0,0,0,1,0
4,1.0,14260,2000,1145,1145,2198,2,4,1,9,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.0,7917,1999,953,953,1647,2,3,1,7,...,0,0,1,0,0,0,0,1,0,0
1456,1.0,13175,1978,1542,2073,2073,2,3,1,7,...,0,0,0,1,0,0,0,1,0,0
1457,1.0,9042,1941,1152,1188,2340,2,4,1,9,...,0,0,0,0,0,0,1,0,1,0
1458,1.0,9717,1950,1078,1078,1078,1,2,1,5,...,0,0,0,1,0,0,0,0,1,0
1459,1.0,9937,1965,1256,1256,1256,1,3,1,6,...,0,0,0,1,0,0,0,1,0,0

In [81]:
lm_bad = sm.OLS(Y1, X_11)
fit_bad = lm_bad.fit()

In [82]:
fit_bad.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.827
Model:                            OLS   Adj. R-squared:                  0.823
Method:                 Least Squares   F-statistic:                     188.9
Date:                Tue, 22 Nov 2022   Prob (F-statistic):               0.00
Time:                        10:30:03   Log-Likelihood:                -17263.
No. Observations:                1460   AIC:                         3.460e+04
Df Residuals:                    1423   BIC:                         3.480e+04
Df Model:                          36
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const           9.647e+04   1.34e+06      0.072      0.943   -2.54e+06    2.73e+06
LotArea            0.6921      0.094      7.341      0.000       0.507       0.877
YearBuilt        553.1168     51.604     10.718      0.000     451.888     654.345
TotalBsmtSF       13.9886      3.873      3.611      0.000       6.390      21.587
1stFlrSF           8.1477      4.501      1.810      0.070      -0.682      16.977
GrLivArea         50.2424      3.921     12.814      0.000      42.551      57.934
FullBath        3449.7450   2496.737      1.382      0.167   -1447.935    8347.425
BedroomAbvGr   -4885.3726   1652.972     -2.956      0.003   -8127.897   -1642.848
KitchenAbvGr   -2.362e+04   4709.383     -5.016      0.000   -3.29e+04   -1.44e+04
TotRmsAbvGrd    2809.2050   1191.559      2.358      0.019     471.803    5146.607
OpenPorchSF      -15.3840     14.479     -1.062      0.288     -43.787      13.019
YrSold          -571.3209    666.952     -0.857      0.392   -1879.635     736.993
HeatingQC_Fa   -1554.7405   5502.968     -0.283      0.778   -1.23e+04    9240.060
HeatingQC_Gd   -2783.7444   2711.524     -1.027      0.305   -8102.759    2535.270
HeatingQC_Po    -1.24e+04   3.39e+04     -0.366      0.714   -7.89e+04    5.41e+04
HeatingQC_TA   -3413.1297   2498.723     -1.366      0.172   -8314.706    1488.447
CentralAir_Y    2619.9261   4499.547      0.582      0.560   -6206.532    1.14e+04
OverallQual_2  -1.182e+04    3.9e+04     -0.303      0.762   -8.83e+04    6.47e+04
OverallQual_3   -1.85e+04   3.56e+04     -0.520      0.603   -8.83e+04    5.13e+04
OverallQual_4   -1.68e+04   3.52e+04     -0.478      0.633   -8.58e+04    5.22e+04
OverallQual_5  -1.333e+04   3.52e+04     -0.378      0.705   -8.25e+04    5.58e+04
OverallQual_6  -7718.7674   3.52e+04     -0.219      0.827   -7.68e+04    6.14e+04
OverallQual_7   7532.4725   3.53e+04      0.213      0.831   -6.18e+04    7.69e+04
OverallQual_8   4.635e+04   3.55e+04      1.306      0.192   -2.33e+04    1.16e+05
OverallQual_9   1.055e+05    3.6e+04      2.928      0.003    3.48e+04    1.76e+05
OverallQual_10  1.164e+05   3.69e+04      3.157      0.002    4.41e+04    1.89e+05
OverallCond_2   1.612e+04   5.07e+04      0.318      0.751   -8.33e+04    1.16e+05
OverallCond_3   1.113e+04   4.78e+04      0.233      0.816   -8.27e+04    1.05e+05
OverallCond_4   2.391e+04   4.86e+04      0.492      0.623   -7.14e+04    1.19e+05
OverallCond_5   3.254e+04   4.85e+04      0.672      0.502   -6.25e+04    1.28e+05
OverallCond_6    4.24e+04   4.84e+04      0.875      0.381   -5.26e+04    1.37e+05
OverallCond_7    4.98e+04   4.84e+04      1.028      0.304   -4.52e+04    1.45e+05
OverallCond_8   5.314e+04   4.85e+04      1.095      0.274   -4.21e+04    1.48e+05
OverallCond_9   6.288e+04   4.89e+04      1.285      0.199   -3.31e+04    1.59e+05
KitchenQual_3   2383.2017   6048.589      0.394      0.694   -9481.907    1.42e+04
KitchenQual_4   8817.3759   6478.375      1.361      0.174   -3890.815    2.15e+04
KitchenQual_5   2.825e+04   7863.316      3.592      0.000    1.28e+04    4.37e+04
==============================================================================
Omnibus:                     1162.341   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           238646.709
Skew:                          -2.796   Prob(JB):                         0.00
Kurtosis:                      65.383   Cond. No.                     2.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [88]:
-1.182e+04 + -1.85e+04 + -1.68e+04 + -1.333e+04 + -7718.7674 + 7532.4725 + 4.635e+04 + 1.055e+05 + 1.164e+05

207613.70510000002

In [83]:
X_11.corr()

,const,LotArea,YearBuilt,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,...,OverallCond_3,OverallCond_4,OverallCond_5,OverallCond_6,OverallCond_7,OverallCond_8,OverallCond_9,KitchenQual_3,KitchenQual_4,KitchenQual_5
const,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LotArea,NaN,1.000000,0.014228,0.260833,0.299475,0.263116,0.126031,0.119690,-0.017784,0.190015,...,-0.011707,0.008570,0.010614,-0.008711,0.009165,-0.027571,0.010745,-0.031154,0.004941,0.073587
YearBuilt,NaN,0.014228,1.000000,0.391452,0.281986,0.199010,0.468271,-0.070651,-0.174800,0.095589,...,-0.100319,-0.185082,0.611566,-0.220338,-0.296643,-0.212190,-0.141688,-0.459792,0.435315,0.204430
TotalBsmtSF,NaN,0.260833,0.391452,1.000000,0.819530,0.454868,0.323722,0.050450,-0.068901,0.285573,...,-0.053208,-0.062776,0.258064,-0.088112,-0.141653,-0.094958,-0.048260,-0.311190,0.173052,0.360271
1stFlrSF,NaN,0.299475,0.281986,0.819530,1.000000,0.566024,0.380637,0.127401,0.068101,0.409516,...,-0.017400,-0.014190,0.183731,-0.082369,-0.094279,-0.096810,-0.014676,-0.273566,0.133058,0.347257
GrLivArea,NaN,0.263116,0.199010,0.454868,0.566024,1.000000,0.630012,0.521270,0.100063,0.825489,...,-0.055737,-0.017714,0.178870,-0.108760,-0.088368,-0.066207,0.073120,-0.350179,0.226253,0.306604
FullBath,NaN,0.126031,0.468271,0.323722,0.380637,0.630012,1.000000,0.363252,0.133115,0.554784,...,-0.068321,-0.078392,0.366209,-0.172440,-0.192736,-0.095836,-0.004405,-0.418698,0.372642,0.174759
BedroomAbvGr,NaN,0.119690,-0.070651,0.050450,0.127401,0.521270,0.363252,1.000000,0.198597,0.676620,...,0.002195,0.050356,-0.017516,-0.009651,0.013007,-0.009246,0.027152,0.017080,0.009025,-0.038717
KitchenAbvGr,NaN,-0.017784,-0.174800,-0.068901,0.068101,0.100063,0.133115,0.198597,1.000000,0.256045,...,0.020029,0.150031,-0.001494,-0.038979,-0.040708,-0.019437,-0.000629,0.160255,-0.154113,-0.057338
TotRmsAbvGrd,NaN,0.190015,0.095589,0.285573,0.409516,0.825489,0.554784,0.676620,0.256045,1.000000,...,-0.045313,0.014113,0.124804,-0.095359,-0.058424,-0.041433,0.057468,-0.210428,0.110562,0.247358
OpenPorchSF,NaN,0.084774,0.188686,0.247264,0.211671,0.330224,0.259977,0.093810,-0.070091,0.234192,...,-0.068115,-0.017653,0.142369,-0.086784,-0.077105,-0.015882,0.061922,-0.221313,0.160655,0.165194
YrSold,NaN,-0.014261,-0.013618,-0.014969,-0.013604,-0.036526,-0.019669,-0.036014,0.031687,-0.034516,...,0.022294,-0.030625,-0.049639,0.026525,0.015994,0.024460,0.038339,-0.000597,-0.008453,0.013122
HeatingQC_Fa,NaN,-0.013661,-0.182534,-0.116785,-0.081264,-0.077747,-0.094526,-0.030105,0.064193,-0.040662,...,0.092665,0.119516,-0.065576,-0.004604,0.023206,-0.042443,-0.023050,0.086197,-0.113797,-0.050532
HeatingQC_Gd,NaN,-0.013072,-0.185920,-0.123598,-0.107498,-0.073952,-0.094410,-0.001836,0.031623,-0.047454,...,-0.016024,0.024681,-0.135821,0.031259,0.048650,0.137314,0.035869,0.094740,-0.051679,-0.084048
HeatingQC_Po,NaN,-0.014475,-0.026245,-0.020143,-0.024363,-0.035508,-0.026862,-0.027815,-0.005536,-0.024456,...,-0.003456,-0.005277,-0.029675,0.057320,-0.010581,-0.005963,-0.003238,0.026001,-0.021437,-0.007099
HeatingQC_TA,NaN,0.011328,-0.285738,-0.157888,-0.105195,-0.187905,-0.253677,0.050120,0.130242,-0.127443,...,0.088973,0.087707,-0.174932,0.143839,0.064550,-0.049386,-0.054953,0.410885,-0.367700,-0.138886
CentralAir_Y,NaN,0.049755,0.381831,0.207958,0.146953,0.093666,0.109326,0.007872,-0.246797,0.034509,...,-0.179236,-0.219229,0.142298,-0.019126,0.018697,-0.004041,0.032631,-0.117606,0.187691,0.060542
OverallQual_2,NaN,-0.012173,-0.054507,-0.073748,-0.069271,-0.081441,-0.074023,-0.103854,-0.009595,-0.079623,...,0.227194,-0.009146,-0.020945,-0.020725,-0.018339,-0.010335,-0.005613,-0.015437,-0.037156,-0.012304
OverallQual_3,NaN,-0.025492,-0.150542,-0.135217,-0.064414,-0.088913,-0.056723,-0.060181,0.108842,-0.044810,...,0.120709,0.158779,-0.109829,0.024137,-0.030670,0.000373,-0.014577,0.069905,-0.084479,-0.031957
OverallQual_4,NaN,-0.047076,-0.223636,-0.202439,-0.171509,-0.228625,-0.204863,-0.119588,0.098853,-0.184029,...,0.058834,0.202294,-0.108381,0.026660,0.019773,-0.043518,-0.015549,0.180341,-0.188892,-0.079664
OverallQual_5,NaN,-0.022262,-0.334679,-0.178214,-0.156649,-0.307964,-0.375476,0.020809,0.122369,-0.184333,...,0.002398,0.043716,-0.252094,0.144511,0.147358,0.066984,-0.025046,0.369886,-0.311980,-0.116960
OverallQual_6,NaN,-0.028830,-0.070583,-0.098891,-0.114593,-0.055399,-0.043693,0.028769,-0.059976,-0.064373,...,-0.004888,-0.069679,-0.095869,0.076592,0.060911,0.083744,-0.033946,0.146617,-0.073985,-0.146706
OverallQual_7,NaN,0.029621,0.297747,0.061591,0.032674,0.189608,0.315247,0.045948,-0.081706,0.130391,...,-0.057014,-0.080904,0.225917,-0.118690,-0.103967,-0.059186,0.057051,-0.320218,0.392130,-0.077757
OverallQual_8,NaN,0.021215,0.305194,0.296383,0.280059,0.296654,0.257497,0.032738,-0.076250,0.202125,...,-0.047596,-0.061601,0.231597,-0.124940,-0.102492,-0.062303,0.008254,-0.341612,0.287122,0.157148
OverallQual_9,NaN,0.050759,0.195294,0.268901,0.260878,0.186387,0.144929,-0.036050,-0.036835,0.186333,...,-0.022993,-0.035112,0.145518,-0.079564,-0.070405,-0.039675,-0.021547,-0.175398,-0.076522,0.514111
OverallQual_10,NaN,0.104730,0.076307,0.299176,0.287092,0.316041,0.155858,0.018298,-0.023625,0.197419,...,-0.014747,-0.022520,0.061032,-0.034605,-0.045155,-0.025446,0.088080,-0.112494,-0.053496,0.338304
OverallCond_2,NaN,-0.010344,-0.066533,0.009781,0.016196,-0.000855,-0.038859,-0.033529,0.040833,0.010181,...,-0.007737,-0.011816,-0.066447,-0.026774,-0.023692,-0.013351,-0.007251,-0.012126,-0.048001,0.030520
OverallCond_3,NaN,-0.011707,-0.100319,-0.053208,-0.017400,-0.055737,-0.068321,0.002195,0.020029,-0.045313,...,1.000000,-0.026604,-0.149612,-0.060285,-0.053346,-0.030062,-0.016326,0.088852,-0.097307,-0.035791
OverallCond_4,NaN,0.008570,-0.185082,-0.062776,-0.014190,-0.017714,-0.078392,0.050356,0.150031,0.014113,...,-0.026604,1.000000,-0.228470,-0.092061,-0.081464,-0.045907,-0.024931,0.122388,-0.136188,-0.054656
OverallCond_5,NaN,0.010614,0.611566,0.258064,0.183731,0.178870,0.366209,-0.017516,-0.001494,0.124804,...,-0.149612,-0.228470,1.000000,-0.517712,-0.458117,-0.258162,-0.140202,-0.268709,0.240750,0.129909
OverallCond_6,NaN,-0.008711,-0.220338,-0.088112,-0.082369,-0.108760,-0.172440,-0.009651,-0.038979,-0.095359,...,-0.060285,-0.092061,-0.517712,1.000000,-0.184596,-0.104025,-0.056494,0.228871,-0.174322,-0.087973
OverallCond_7,NaN,0.009165,-0.296643,-0.141653,-0.094279,-0.088368,-0.192736,0.013007,-0.040708,-0.058424,...,-0.053346,-0.081464,-0.458117,-0.184596,1.000000,-0.092051,-0.049990,0.062293,-0.061461,-0.047152
OverallCond_8,NaN,-0.027571,-0.212190,-0.094958,-0.096810,-0.066207,-0.095836,-0.009246,-0.019437,-0.041433,...,-0.030062,-0.045907,-0.258162,-0.104025,-0.092051,1.000000,-0.028171,0.004767,0.000654,-0.011666
OverallCond_9,NaN,0.010745,-0.141688,-0.048260,-0.014676,0.073120,-0.004405,0.027152,-0.000629,0.057468,...,-0.016326,-0.024931,-0.140202,-0.056494,-0.049990,-0.028171,1.000000,-0.079560,0.082237,0.010977
KitchenQual_3,NaN,-0.031154,-0.459792,-0.311190,-0.273566,-0.350179,-0.418698,0.017080,0.160255,-0.210428,...,0.088852,0.122388,-0.268709,0.228871,0.062293,0.004767,-0.079560,1.000000,-0.824457,-0.273027
KitchenQual_4,NaN,0.004941,0.435315,0.173052,0.133058,0.226253,0.372642,0.009025,-0.154113,0.110562,...,-0.097307,-0.136188,0.240750,-0.174322,-0.061461,0.000654,0.082237,-0.824457,1.000000,-0.222036
KitchenQual_5,NaN,0.073587,0.204430,0.360271,0.347257,0.306604,0.174759,-0.038717,-0.057338,0.247358,...,-0.035791,-0.054656,0.129909,-0.087973,-0.047152,-0.011666,0.010977,-0.273027,-0.222036,1.000000

In [84]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

pd.Series([variance_inflation_factor(X_11.values, i) for i in range(X_11.shape[1])],index=X_11.columns)

const             2.348763e+06
LotArea           1.154120e+00
YearBuilt         3.165523e+00
TotalBsmtSF       3.762818e+00
1stFlrSF          3.945775e+00
GrLivArea         5.531454e+00
FullBath          2.465444e+00
BedroomAbvGr      2.369486e+00
KitchenAbvGr      1.403094e+00
TotRmsAbvGrd      4.887957e+00
OpenPorchSF       1.199321e+00
YrSold            1.022413e+00
HeatingQC_Fa      1.280819e+00
HeatingQC_Gd      1.321352e+00
HeatingQC_Po      1.024743e+00
HeatingQC_TA      1.687060e+00
CentralAir_Y      1.606071e+00
OverallQual_2     4.068302e+00
OverallQual_3     2.232861e+01
OverallQual_4     1.178654e+02
OverallQual_5     3.205368e+02
OverallQual_6     3.085008e+02
OverallQual_7     2.780856e+02
OverallQual_8     1.672888e+02
OverallQual_9     4.842287e+01
OverallQual_10    2.157727e+01
OverallCond_2     1.142992e+01
OverallCond_3     5.023608e+01
OverallCond_4     1.154697e+02
OverallCond_5     7.535440e+02
OverallCond_6     4.367257e+02
OverallCond_7     3.694266e+02
OverallCond_8     1.439810e+02
OverallCond_9     4.636914e+01
KitchenQual_3     1.192626e+01
KitchenQual_4     1.314959e+01
KitchenQual_5     5.144240e+00
dtype: float64

In [85]:
from statsmodels.stats.diagnostic import het_breuschpagan

In [86]:
result_bp_test = het_breuschpagan(fit_bad.resid, lm_bad.exog)
bp_lm_statistic = result_bp_test[0]
bp_lm_pval = result_bp_test[1]
bp_F_statistic= result_bp_test[2] 
bp_F_pval = result_bp_test[3]
bp_test_output=pd.Series(result_bp_test[0:4],index=['bp_lm_statistic','bp_lm_pval','bp_F_statistic','bp_F_pval'])   
print(bp_test_output)

bp_lm_statistic     4.990804e+02
bp_lm_pval          7.192809e-83
bp_F_statistic      2.052985e+01
bp_F_pval          7.389026e-104
dtype: float64

In [101]:
X2 = pd.read_csv("X2.csv")
X2_Test = pd.read_csv("X2_Test.csv")
Y2 = pd.read_csv("Y2.csv")
model_test = pd.read_csv("model_test.csv")
lm_bad2 = sm.OLS(Y2, X2)
fit_bad2 = lm_bad2.fit()

In [90]:
fit_bad2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.782
Model:                            OLS   Adj. R-squared:                  0.780
Method:                 Least Squares   F-statistic:                     399.5
Date:                Tue, 22 Nov 2022   Prob (F-statistic):               0.00
Time:                        10:41:36   Log-Likelihood:                -17431.
No. Observations:                1460   AIC:                         3.489e+04
Df Residuals:                    1446   BIC:                         3.496e+04
Df Model:                          13
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const           4.844e+04    1.1e+04      4.403      0.000    2.69e+04       7e+04
LotArea            0.8995      0.102      8.844      0.000       0.700       1.099
OverallQual     1.961e+04   1186.428     16.531      0.000    1.73e+04    2.19e+04
Age             -468.6664     46.776    -10.019      0.000    -560.422    -376.911
GrLivArea         56.1371      2.870     19.562      0.000      50.508      61.766
FullBath       -3978.0505   2610.505     -1.524      0.128   -9098.832    1142.731
CentralAir_Y    8806.1208   4459.959      1.974      0.049      57.440    1.76e+04
KitchenQual_Fa -6.592e+04   8125.524     -8.112      0.000   -8.19e+04      -5e+04
KitchenQual_Gd -5.739e+04   4340.452    -13.223      0.000   -6.59e+04   -4.89e+04
KitchenQual_TA -6.946e+04   4928.410    -14.093      0.000   -7.91e+04   -5.98e+04
YrSold_2007     1568.4185   2939.968      0.533      0.594   -4198.641    7335.478
YrSold_2008    -1075.4584   3000.933     -0.358      0.720   -6962.107    4811.190
YrSold_2009    -1938.2336   2923.262     -0.663      0.507   -7672.522    3796.055
YrSold_2010     1440.4850   3515.822      0.410      0.682   -5456.173    8337.143
==============================================================================
Omnibus:                      469.972   Durbin-Watson:                   1.982
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            43484.271
Skew:                          -0.492   Prob(JB):                         0.00
Kurtosis:                      29.718   Cond. No.                     1.93e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.93e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [92]:
display(X2_Test)

,const,LotArea,OverallQual,Age,GrLivArea,FullBath,YrSold,CentralAir_Y,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA
0,1.0,11622,5,61,896,1,2010,1,0,0,1
1,1.0,14267,6,64,1329,1,2010,1,0,1,0
2,1.0,13830,5,25,1629,2,2010,1,0,0,1
3,1.0,9978,6,24,1604,2,2010,1,0,1,0
4,1.0,5005,8,30,1280,2,2010,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
1454,1.0,1936,4,52,1092,1,2006,1,0,0,1
1455,1.0,1894,4,52,1092,1,2006,1,0,0,1
1456,1.0,20000,5,62,1224,1,2006,1,0,0,1
1457,1.0,10441,5,30,970,1,2006,1,0,0,1
1458,1.0,9627,7,29,2000,2,2006,1,0,0,1

In [102]:
display(model_test)

,LotArea,OverallQual,Age,CentralAir,GrLivArea,FullBath,KitchenQual,YrSold
0,11622,5,61,Y,896,1,TA,2010
1,14267,6,64,Y,1329,1,Gd,2010
2,13830,5,25,Y,1629,2,TA,2010
3,9978,6,24,Y,1604,2,Gd,2010
4,5005,8,30,Y,1280,2,Gd,2010
...,...,...,...,...,...,...,...,...
1454,1936,4,52,Y,1092,1,TA,2006
1455,1894,4,52,Y,1092,1,TA,2006
1456,20000,5,62,Y,1224,1,TA,2006
1457,10441,5,30,Y,970,1,TA,2006
1458,9627,7,29,Y,2000,2,TA,2006

In [93]:
X2_Test['LotArea'].mean()

9819.161069225496

In [94]:
X2_Test['OverallQual'].mean()

6.078821110349555

In [95]:
X2_Test['Age'].mean()

50.64222069910898

In [96]:
X2_Test['GrLivArea'].mean()

1486.0459218642907

In [97]:
X2_Test['FullBath'].mean()

1.570938999314599

In [98]:
X2_Test['YrSold'].value_counts()

2007    363
2008    318
2009    309
2006    305
2010    164
Name: YrSold, dtype: int64

In [99]:
X2_Test['CentralAir_Y'].value_counts()

1    1358
0     101
Name: CentralAir_Y, dtype: int64

In [103]:
model_test['KitchenQual'].value_counts()

TA    757
Gd    566
Ex    105
Fa     31
Name: KitchenQual, dtype: int64

In [105]:
9819.161069225496*0.8995 + 6*1.961e+04 + 51* (-468.6664) + 1486*56.1371 + 2*(-3978.0505) + 1568.4185 + 8806.1208 + (-6.946e+04) + 4.844e+04

167408.51788176832